optimizer:
  name: adam
  lr: 1.0e-3
  weight_decay: 0

train:
  epoch: 200
  batch_size: 4096
  save_model: false
  loss: pairwise
  test_step: 1
  #pretrain_path: ./checkpoint/xxxx.pth
  reproducible: true
  seed: 421
  spline_order: 2
  grid_size: 2
  trainer: AdaGCLKANTrainer
  
  
# 'hidden_channels':8,
#             'mp_layers': dataset_layers[args.dataset],
#             'hidden_layers':2,
#             'lr':0.01,
#             'dropout':0,
#             'spline_order':2,
#             'grid_size':2,
#             'model_type':args.model_type,
#             'architecture':args.architecture,
#             'num_features': data.num_features,
#             'num_classes': data.num_classes,
#             'patience': args.patience,
#             'heads': args.heads





test:
  metrics: [recall, ndcg]
  k: [10, 20, 40]
  batch_size: 256

data:
  type: general_cf # choose in {general_cf, multi_behavior, sequential, social}
  name: yelp

model:
  name: adagcl_kan # case-insensitive
  layer_num: 3
  reg_weight: 1.0e-5
  cl_weight: 0.1
  ib_weight: 1.0e-2
  temperature: 0.5
  embedding_size: 32
  gamma: -0.95
  zeta: 1.05
  init_temperature: 2.0
  temperature_decay: 0.98
  lambda0: 1.0e-4
  spline_order: 2
  grid_size: 4
  
